*1.Load Libraries*

In [55]:
import numpy as np 
import pandas as pd

*2.Load Dataset*

In [56]:
# -------------------- 2015,2016,2017,2018,------------------------>
df_2015 = pd.read_csv('../data/raw/2015.csv')
df_2016 = pd.read_csv('../data/raw/2016.csv')
df_2017 = pd.read_csv('../data/raw/2017.csv')
df_2018 = pd.read_csv('../data/raw/2018.csv')
df_2019 = pd.read_csv('../data/raw/2019.csv')
df_2020 = pd.read_csv('../data/raw/2020.csv')
df_2021 = pd.read_csv('../data/raw/2021.csv')
df_2023 = pd.read_csv('../data/raw/2023.csv')

In [57]:
# ------------------SHAPE--------------------------->
print('20215 dimension : ', df_2015.shape)
print('20216 dimension : ', df_2016.shape)
print('20217 dimension : ', df_2017.shape)
print('20218 dimension : ', df_2018.shape)
print('20219 dimension : ', df_2019.shape)

20215 dimension :  (158, 12)
20216 dimension :  (157, 13)
20217 dimension :  (155, 12)
20218 dimension :  (156, 9)
20219 dimension :  (156, 9)

*3.Check How To Look Like Columns*

In [58]:
# --------------------2015-columns---------------------------->
print('COLUMNS 2015 :\n', df_2015.columns.to_list())

# --------------------2016-columns---------------------------->
print('COLUMNS 2016 :\n', df_2016.columns.to_list())

# --------------------2017-columns---------------------------->
print('COLUMNS 2017 :\n', df_2017.columns.to_list())

# --------------------2018-columns---------------------------->
print('COLUMNS 2018 :\n', df_2018.columns.to_list())

# --------------------2019-columns---------------------------->
print('COLUMNS 2019:\n', df_2019.columns.to_list())

COLUMNS 2015 :
 ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Standard Error', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
COLUMNS 2016 :
 ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Lower Confidence Interval', 'Upper Confidence Interval', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
COLUMNS 2017 :
 ['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high', 'Whisker.low', 'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Generosity', 'Trust..Government.Corruption.', 'Dystopia.Residual']
COLUMNS 2018 :
 ['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']
COLUMNS 2019:
 ['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

In [59]:
# 2020 to 2024 dataset has some different columns ,Firstly i deal with that
df_2020.columns.tolist()

['Country name',
 'Regional indicator',
 'Ladder score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Logged GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [60]:
# I want to delete some columns from 2020, 2021, 2023
df_2021_2023 = [df_2020, df_2021, df_2023]

In [61]:
columns_to_drop = [
     'upperwhisker', 'lowerwhisker',
    'Standard error of ladder score',
    'Ladder score in Dystopia', 'Dystopia + residual'
] 
# Drop all columns starting with 'Explained by'
columns_to_drop += [col for col in df_2021_2023[0].columns if col.startswith('Explained by')]

In [62]:
for i in range(len(df_2021_2023)):
    df_2021_2023[i] = df_2021_2023[i].drop(columns=columns_to_drop)

In [63]:
df_2020, df_2021, df_2023 = df_2021_2023

In [64]:
df_2020.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

4. Standardize Column Names

In [70]:
# Different years use different names for the same data -→ unify them.

rename_dict = {
    "Country or region": "Country" ,
    'Country name':'Country',
    
    'Regional indicator':'Region',

    "Happiness Score": "HappinessScore",
    "Happiness.Score": "HappinessScore",
    "Score":"HappinessScore",
    'Ladder score':"HappinessScore",
    
    # "Life Ladder": "HappinessScore",
    "Happiness.Rank":"HappinessRank",
    "Happiness Rank":"HappinessRank",
    "Overall rank":"HappinessRank",

    "Economy (GDP per Capita)": "GDP per Capita",
    "Economy..GDP.per.Capita.": "GDP per Capita",
    'Logged GDP per capita':'GDP per Capita',
    "GDP per capita":"GDP per Capita",

    "Healthy life expectancy": "LifeExpectancy",
    "Health (Life Expectancy)": "LifeExpectancy",
    "Health..Life.Expectancy.":"LifeExpectancy",

    "Social support": "SocialSupport",
    "Family": "SocialSupport",
    "Freedom to make life choices": "Freedom",
    "Freedom": "Freedom",
    
    "Perceptions of corruption": "Corruption",
    "Trust (Government Corruption)": "Corruption",
    "Trust..Government.Corruption.":"Corruption"
}

# Apply rename for all dataframes
df_2015.rename(columns=rename_dict, inplace=True)
df_2016.rename(columns=rename_dict, inplace=True)
df_2017.rename(columns=rename_dict, inplace=True)
df_2018.rename(columns=rename_dict, inplace=True)
df_2019.rename(columns=rename_dict, inplace=True)
df_2020.rename(columns=rename_dict, inplace=True)
df_2021.rename(columns=rename_dict, inplace=True)
df_2023.rename(columns=rename_dict, inplace=True)

In [71]:
# Add the year columns according to dataset
# ----------------------Adding Years-------------------->
df_2015['Year'] = 2015
df_2016['Year'] = 2016
df_2017['Year'] = 2017
df_2018['Year'] = 2018
df_2019['Year'] = 2019
df_2020['Year'] = 2020
df_2021['Year'] = 2021
df_2023['Year'] = 2023
# Let check it
df_2018.columns

Index(['HappinessRank', 'Country', 'HappinessScore', 'GDP per Capita',
       'SocialSupport', 'LifeExpectancy', 'Freedom', 'Generosity',
       'Corruption', 'Year'],
      dtype='object')

5.Mergs-dataset

In [72]:
# ------------------------------CONCATINATION------------------------------>
df = pd.concat([df_2015, df_2016, df_2017, df_2018, df_2019,df_2020,df_2021, df_2023], ignore_index=True)

# let see the first five data
df.head()

,Country,Region,HappinessRank,HappinessScore,Standard Error,GDP per Capita,SocialSupport,LifeExpectancy,Freedom,Corruption,Generosity,Dystopia Residual,Year,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low,Dystopia.Residual
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN,NaN,NaN,NaN

In [73]:
# CheckOut the Dimension of dataset
print(f"Rows & Columns : {df.shape}")

Rows & Columns : (1221, 18)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1221 entries, 0 to 1220
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Country                    1221 non-null   object
 1   Region                     617 non-null    object
 2   HappinessRank              782 non-null    float64
 3   HappinessScore             1221 non-null   float64
 4   Standard Error             158 non-null    float64
 5   GDP per Capita             1221 non-null   float64
 6   SocialSupport              1221 non-null   float64
 7   LifeExpectancy             1220 non-null   float64
 8   Freedom                    1221 non-null   float64
 9   Corruption                 1220 non-null   float64
 10  Generosity                 1221 non-null   float64
 11  Dystopia Residual          315 non-null    float64
 12  Year                       1221 non-null   int64
 13  Lower Confidence Interval  157 non-null    float64
 14  Upper Confidence Interval  157 non-null    float64
 15  Whisker.high               155 non-null    float64
 16  Whisker.low                155 non-null    float64
 17  Dystopia.Residual          155 non-null    float64
dtypes: float64(15), int64(1), object(2)
memory usage: 171.8+ KB

In [76]:
df_final = df[['Year','Corruption','GDP per Capita','SocialSupport','LifeExpectancy','Freedom','Generosity','HappinessScore']]

In [77]:
df_final.head()

,Year,Corruption,GDP per Capita,SocialSupport,LifeExpectancy,Freedom,Generosity,HappinessScore
0,2015,0.41978,1.39651,1.34951,0.94143,0.66557,0.29678,7.587
1,2015,0.14145,1.30232,1.40223,0.94784,0.62877,0.43630,7.561
2,2015,0.48357,1.32548,1.36058,0.87464,0.64938,0.34139,7.527
3,2015,0.36503,1.45900,1.33095,0.88521,0.66973,0.34699,7.522
4,2015,0.32957,1.32629,1.32261,0.90563,0.63297,0.45811,7.427

In [78]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1221 entries, 0 to 1220
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            1221 non-null   int64
 1   Corruption      1220 non-null   float64
 2   GDP per Capita  1221 non-null   float64
 3   SocialSupport   1221 non-null   float64
 4   LifeExpectancy  1220 non-null   float64
 5   Freedom         1221 non-null   float64
 6   Generosity      1221 non-null   float64
 7   HappinessScore  1221 non-null   float64
dtypes: float64(7), int64(1)
memory usage: 76.4 KB

In [79]:
df_final.to_csv('../data/processed/world_happiness_cleaned.csv', index=False)